### ISSUE TITLE
Support custom data type conversion in query

### ISSUE THREAD

**Issue by jonnyyu** [koxudaxi/py-data-api#14]
**Is your feature request related to a problem? Please describe.**

First, thanks for making pydataapi, it helps using Data-Api a lot!.
With it, I can define Table like below:

machines = Table('machines', metaData, Column('ip', IPAddressType())
My IPAddressType can convert between VarBinary(16) and ip_address.IPAddress.
I can see the conversion from IPAddress to VarBinary(16) working in insertion.
But the results are still in bytes when selecting from machines table.

**Describe the solution you'd like**

I hope execute(sql) when it is a sql object, it can help convert the custom data type back before returning the results.

**Describe alternatives you've considered**

**Additional context**

**Comment by koxudaxi** [comment]
@jonnyyu 
Thank you for using py-data-api

Yes,py-data-api uses only Table() of sqlalchemy for building a raw SQL statement.

I have checked the document of a custom data type. ( I had not known how to work the data type converter)

I think about the implementation of the feature. 
py-data-api can call the method to convert raw data from the Table() object.
https://docs.sqlalchemy.org/en/13/core/custom_types.html#sqlalchemy.types.TypeDecorator.process_result_value

## Example
```python
from sqlalchemy import String, TypeDecorator, Column, MetaData, Table
from sqlalchemy.dialects.mysql import mysqldb

class MyDate(TypeDecorator):
  ...

metadata = MetaData()
t = Table('user', metadata, Column('time', MyDate()))
print(t.columns.time.type.process_result_value('2019-10-10', mysqldb))
# date(2019, 10, 10)
```
I seem good to call the method in `DataAPI.execute()` and retrun converted value.

Also, The feature can be enabled with a keyword argument.
## Example
```pyhton
data_api.execute(query, result_processor=True) # or more good keyword
```
How did you think it?

**Comment by koxudaxi** [comment]
I will implement this feature when I have time.

**Comment by koxudaxi** [comment]
@jonnyyu
I have released a new version with the feature.
If you still using the library then, please try the latest version.
