### ISSUE TITLE
Chalice does not detect permissions when using pydatapi

### ISSUE THREAD

**Issue by Rubyj** [koxudaxi/py-data-api#28]
Usually `chalice` will automatically detect permissions the lambda function needs based on what is used in the code. For example, when we get a secret from SecretsManager, `chalice` would give that permission to the IAM role for lambda. When I use `pydataapi` I do not seem to get these permissions, like access to secrets, added to my lambda function IAM role  when I `chalice deploy`.

Is this a `pydataapi` bug or a `chalice` bug.

**Comment by koxudaxi** [comment]
I have checked the source code of `chalice`.
`chalice` analyzes your code dynamically. 
However, The analyzer doesn't parse any library include `pydataapi`.

I think a way to resolve the problem of adding permission.
We should call the client boto3 to detect using aws service by `chalice`.
I have tested the method.
app.py
```python
...
if False: # never called
    import boto3
    client = boto3.client('rds-data')
    client.execute_statement()
...
```

result 
<img width="785" alt="スクリーンショット 2019-10-18 10 48 25" src="https://user-images.githubusercontent.com/630670/67059635-d5724380-f194-11e9-8261-21178da55508.png">

**Comment by Rubyj** [comment]
> I have checked the source code of `chalice`.
> `chalice` analyzes your code dynamically.
> However, The analyzer doesn't parse any library include `pydataapi`.
> 
> I think a way to resolve the problem of adding permission.
> We should call the client boto3 to detect using aws service by `chalice`.
> I have tested the method.
> app.py
> 
> ```python
> ...
> if False: # never called
>     import boto3
>     client = boto3.client('rds-data')
>     client.execute_statement()
> ...
> ```
> 
> result
> <img alt="スクリーンショット 2019-10-18 10 48 25" width="785" src="https://user-images.githubusercontent.com/630670/67059635-d5724380-f194-11e9-8261-21178da55508.png">
> 
> This is not the best way, but it helps your development 😉

Ok! I will either do this or manually add the IAM role. It would be nice if `chalice` was smart enough to know the package requires permissions!
