### ISSUE TITLE
Use names instead of ARN

### ISSUE THREAD

**Issue by Rubyj** [koxudaxi/py-data-api#31]
For providing DB cluster ARN and secret ARN, I would like to be able to provide the name instead.

```
aws_args = {'resource_name': 'lambda_function_name',
    'secret_name': 'secret_name',
    'database': 'database'}
```

Maybe we can allow either name or ARN? Boto3 has this ability!
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds-data.html

**Comment by koxudaxi** [comment]
@Rubyj 
Sorry, I don't understand your suggests.
I have a few questions.
First, Did you except to give a name to `connect_args`?

Second, Is The ability this in the boto3 document?
```
resourceArn (string) --
[REQUIRED]

The Amazon Resource Name (ARN) of the Aurora Serverless DB cluster.
...
secretArn (string) --
[REQUIRED]

The name or ARN of the secret that enables access to the DB cluster.
```

**Comment by Rubyj** [comment]
@koxudaxi

Basically, I would like to be able to pass the name of the function to the `connect_args` instead of the full long arn. Does this make sense?

**Comment by koxudaxi** [comment]
> Maybe this could be included in this library?

Yes, maybe...  I'm testing now.

**Comment by Rubyj** [comment]
> > Maybe this could be included in this library?
> 
> Yes, maybe... I'm testing now.

FYI this is how I do it:

`db_arn = client.describe_db_clusters(DBClusterIdentifier=db_name)['DBClusters'][0]['DBClusterArn']`

**Comment by koxudaxi** [comment]
@Rubyj 

> db_arn = client.describe_db_clusters(DBClusterIdentifier=db_name)['DBClusters'][0]['DBClusterArn']

OK, I understand. I will implement it tomorrow.
Thank you for suggenting great idea :)

**Comment by Rubyj** [comment]
I thought about it a little and we could do something like this in dbapi.py

```
class Connection:
    paramstyle = paramstyle
    Error = Error

    def __init__(self, **kwargs: Any) -> None:
        connect_args = ConnectArgs.parse_obj(kwargs)
        if connect_args.resource_name is not None:
            connect_args.resource_arn = client.describe_db_clusters(DBClusterIdentifier=db_name)['DBClusters'][0]['DBClusterArn']

        self._data_api = DataAPI(
            connect_args.resource_arn,
            connect_args.secret_arn,
            connect_args.database,
            connect_args.transaction_id,
            connect_args.client,
            connect_args.rollback_exception,
        )
```
