### ISSUE TITLE
Request: Create a new release reflecting latest commit.

### ISSUE THREAD

**Issue by hyuma** [koxudaxi/py-data-api#54]
I kindly request to create a new release using latest commit.
Current release invokes tons of warnings from pydantic so...

Thank you in advance.

**Comment by koxudaxi** [comment]
Thank you for your request.
I have released a new version as 0.4.14.

**Comment by hyuma** [comment]
Thank you. I confirmed that the one in PyPl has been reflected. https://pypi.org/project/pydataapi/
ありがとうございます！
