### ISSUE TITLE
TIMESTAMP isn't supported by the Postgres+dataapi dialect

### ISSUE THREAD

**Issue by novachok** [koxudaxi/py-data-api#56]
**Describe the bug**
Timestamp columns aren't supported. 
When you are trying to save such filed you'll have an exception:

> column "****" is of type timestamp without time zone but expression is of type character varying

**To Reproduce**
you  have a table like this:

```
create table users (
    id serial primary key,
    username VARCHAR(100) not null,
    seen_at TIMESTAMP null
);
```
you have an entity class like this:

```
class UserEntity(Base):
    __tablename__ = 'users'

    id = Column(Integer, primary_key=True)
    username = Column(String)
    seen_at = Column(DateTime)
```

and the execution plan:
```
user = UserEntity(
    username="user@name", 
    seen_at=datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S")
)

session.add(user)
session.commit()
```

I had spent the time to investigate the issue and what I've found:
the generated options to the `client.execute_statement` are

```
{
    .....
    'sql': 'INSERT INTO users (username, seen_at) VALUES (:username, :seen_at) RETURNING users.id', 
    'parameters': [{
        'name': 'username', 
        'value': {
            'stringValue': 'novachok'
        }
    }, {
        'name': 'seen_at', 
        'value': {
            'stringValue': '2020-02-14 12:46:46.901717'
        }
    }]
}
```

however, **must** contains the **typeHint** in it:

```
{
    .....
    'sql': 'INSERT INTO users (username, seen_at) VALUES (:username, :seen_at) RETURNING users.id', 
    'parameters': [{
        'name': 'username', 
        'value': {
            'stringValue': 'novachok'
        }
    }, {
        'name': 'seen_at', 
        'typeHint': 'TIMESTAMP'
        'value': {
            'stringValue': '2020-02-14 12:46:46.901717'
        }
    }]
}
```

**Comment by koxudaxi** [comment]
Thank you for your report.
I don't know this new option (aka `typeHint`). the document is updated (https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/data-api.html)

I will implement it ASAP

**Comment by koxudaxi** [comment]
@novachok 
I have released a new version as 0.4.15.
Would you please check the feature?

**Comment by koxudaxi** [comment]
I have fixed the `typeHint` which is 0.4.16

I add unittest for timestamp .
https://github.com/koxudaxi/py-data-api/blob/17f8d42cce58c762900c068c69d8051412427045/tests/integration/test_mysql.py#L233-L239

**Comment by novachok** [comment]
cool, I'll test it a litle bit later.

**Comment by novachok** [comment]
I believe we can close this issue. Tested and works well for me.
