### ISSUE TITLE
Issue with regex for catching whether table exists

### ISSUE THREAD

**Issue by vijay-singh** [koxudaxi/py-data-api#73]
**Describe the bug**
The has_table function [here](https://github.com/koxudaxi/py-data-api/blob/master/pydataapi/dialect/base.py#L112) uses a regular expression on the error message to catch if a table does not exist. However, for me, the error message also includes the connection number at the start. As an example:
> (conn=23) Table 'users.user' doesn't exist

As a result, the regular expression does not match and the exception is not caught. We should update the regular expression to handle this, and I'll be putting up a PR to do so. This will enable us to support [Metadata.create_all](https://docs.sqlalchemy.org/en/13/core/metadata.html#sqlalchemy.schema.MetaData.create_all) functionality in SQLAlchemy.

**Comment by vijay-singh** [comment]
Did some more investigation -- this actually has to do with the latest version of the docker image koxudaxi/local-data-api. The integration tests for py-data-api use version 0.4.7, which doesn't have the prefix "(conn=XX)" in the error message, whereas the latest version of local-data-api includes this prefix.

**Comment by koxudaxi** [comment]
@vijay-singh 
Thank you for creating this issue and PR.
I have released a new version as `0.4.21`

I want to improve the library. But, I'm busy with other projects :(
So, I always welcome PR :rocket:
